export interface GlossaryEntry {
  term: string
  simpleDefinition: string
  detailedDefinition: string
  example: string
  category: 'BASIC' | 'TECHNICAL' | 'OPTIONS' | 'MACRO' | 'CRYPTO' | 'INDIA'
  learnMoreUrl?: string
}

export const GLOSSARY: Record<string, GlossaryEntry> = {

  // ─── BASIC ───────────────────────────────────────────────────────────────

  MARKET_CAP: {
    term: 'Market Capitalization',
    simpleDefinition: 'The total value of all shares of a company combined.',
    detailedDefinition: 'Calculated by multiplying the current share price by total number of shares. Large-cap (>₹20,000 Cr) are stable giants. Mid-cap are growing companies. Small-cap are risky but high-potential.',
    example: 'TCS at ₹3,500/share × 370 crore shares = ₹12,95,000 crore market cap — a mega-cap company.',
    category: 'BASIC',
  },
  PE_RATIO: {
    term: 'Price-to-Earnings Ratio (P/E)',
    simpleDefinition: 'How many rupees you pay for every ₹1 the company earns.',
    detailedDefinition: 'A P/E of 25 means you pay ₹25 for every ₹1 of annual profit. Lower P/E can mean cheaper stock, but also depends on industry. Tech companies often have high P/E because of growth expectations.',
    example: 'Reliance P/E of 24 — you pay ₹24 for every ₹1 of profit. Nifty 50 average P/E is ~20.',
    category: 'BASIC',
  },
  EPS: {
    term: 'Earnings Per Share',
    simpleDefinition: 'How much profit a company makes per share.',
    detailedDefinition: 'Total company profit divided by total shares. Higher EPS = company earning more money per share you own. Rising EPS quarter after quarter = healthy, growing company.',
    example: 'TCS EPS ₹120 means for every 1 share you hold, TCS earned ₹120 profit last year.',
    category: 'BASIC',
  },
  DIVIDEND_YIELD: {
    term: 'Dividend Yield',
    simpleDefinition: 'The % of share price paid to you as cash every year.',
    detailedDefinition: 'If a ₹1000 stock pays ₹20 dividend, yield = 2%. Like interest from a bank but from owning shares. Not all companies pay dividends — growth companies usually reinvest profits instead.',
    example: 'Coal India at 8% dividend yield on ₹240 share = ₹19.2 per share paid annually as cash.',
    category: 'BASIC',
  },
  '52W_HIGH': {
    term: '52-Week High',
    simpleDefinition: 'The highest price this stock reached in the past year.',
    detailedDefinition: 'If a stock is near its 52-week high, it is performing well. If it recently broke above the 52-week high, that is often a strong bullish signal attracting momentum buyers.',
    example: 'HDFC Bank 52W High: ₹1,794. Current price ₹1,650 = 8% below its high.',
    category: 'BASIC',
  },
  '52W_LOW': {
    term: '52-Week Low',
    simpleDefinition: 'The lowest price this stock reached in the past year.',
    detailedDefinition: 'A stock near its 52-week low may be undervalued — or in trouble. Requires research. Breaking below 52-week low is a very bearish signal.',
    example: 'ITC 52W Low: ₹380. Current price ₹440 = 16% above the low — recovered but worth watching.',
    category: 'BASIC',
  },
  VOLUME: {
    term: 'Trading Volume',
    simpleDefinition: 'How many shares were bought and sold today.',
    detailedDefinition: 'High volume on a price rise = strong move with conviction. High volume on a fall = serious selling pressure. Low volume moves are less reliable and often reverse. Always check volume.',
    example: 'RELIANCE average volume 4M shares/day. If today shows 8M = 2× normal = something important happening.',
    category: 'BASIC',
  },
  MARKET_BREADTH: {
    term: 'Market Breadth',
    simpleDefinition: 'How many stocks are actually rising vs falling — health of the overall market.',
    detailedDefinition: 'If Nifty rises but only 15 of 50 stocks go up, breadth is poor — the index is being pulled by a few heavyweights. Strong breadth (40+ stocks rising) = broad-based, sustainable rally.',
    example: 'Nifty hit new high with only 20 stocks rising and 30 falling — poor breadth, likely unsustainable.',
    category: 'BASIC',
  },
  RISK_REWARD: {
    term: 'Risk-Reward Ratio',
    simpleDefinition: 'How much you could gain vs how much you could lose on a trade.',
    detailedDefinition: 'R:R of 1:3 means risk ₹1 to potentially gain ₹3. Never take trades with R:R worse than 1:1.5. Good traders aim for 1:2 or better. Position sizing should be based on your maximum acceptable loss.',
    example: 'Entry ₹100, Target ₹130, Stop ₹90. Risk=₹10, Reward=₹30. R:R = 1:3. Excellent trade setup.',
    category: 'BASIC',
  },
  DIVIDEND: {
    term: 'Dividend',
    simpleDefinition: 'Cash paid by a company to shareholders from its profits.',
    detailedDefinition: 'Companies declare dividends per share. You get this cash just for holding the stock. Dividend-paying companies (PSUs, FMCG) are popular for passive income. Growth companies like TCS and INFY pay smaller dividends.',
    example: 'HCL Tech declares ₹18 dividend. If you hold 100 shares = ₹1,800 cash deposited in your account.',
    category: 'BASIC',
  },
  EX_DATE: {
    term: 'Ex-Dividend Date',
    simpleDefinition: 'The cut-off date — you must own the stock BEFORE this date to receive the dividend.',
    detailedDefinition: 'If ex-date is Monday, you must buy by Friday (T+1 settlement). Stocks usually fall by the dividend amount on ex-date as the cash leaves the company. Do not buy just for dividend — you may lose more in price drop.',
    example: 'INFOSYS ex-date July 5. Buy by July 4 to get ₹21 dividend. Stock may fall ₹20-25 on July 5.',
    category: 'BASIC',
  },
  RECORD_DATE: {
    term: 'Record Date',
    simpleDefinition: 'The date the company checks its shareholder list to decide who gets the dividend.',
    detailedDefinition: 'Record date is 1 day after ex-date (T+1 settlement). If you hold shares by ex-date, your name appears in company records on record date and you receive dividend. Both ex-date and record date are announced together.',
    example: 'Ex-date July 5, Record date July 6. Buy by July 4, get dividend. Buy July 5 or after = no dividend.',
    category: 'BASIC',
  },
  IPO: {
    term: 'IPO (Initial Public Offering)',
    simpleDefinition: 'When a private company sells shares to the public for the first time.',
    detailedDefinition: 'Companies raise money by selling shares on NSE/BSE. You apply during subscription period (usually 3 days). Lots are allotted by lottery if oversubscribed. Listing price can be higher or lower than issue price.',
    example: 'Zomato IPO at ₹76. Listed at ₹116 = 52% listing gain. Not all IPOs list higher — check fundamentals.',
    category: 'INDIA',
  },
  BUYBACK: {
    term: 'Share Buyback',
    simpleDefinition: 'When a company buys back its own shares from the market.',
    detailedDefinition: 'Reduces number of shares outstanding → EPS rises → remaining shares worth more. Usually a positive signal — company thinks its own stock is undervalued. Also returns cash to shareholders.',
    example: 'TCS buyback at ₹4,500/share when market price is ₹3,800 = premium of ₹700. Existing shareholders benefit.',
    category: 'BASIC',
  },
  BONUS_SHARE: {
    term: 'Bonus Share',
    simpleDefinition: 'Free extra shares given to existing shareholders.',
    detailedDefinition: '1:1 bonus = you get 1 free share for every 1 you hold. Price adjusts proportionally (stock splits effectively). No cash benefit immediately, but more shares available. Shows company confidence.',
    example: 'HDFC Life announces 1:1 bonus. You hold 100 shares at ₹650 → becomes 200 shares at ₹325 = same total value.',
    category: 'BASIC',
  },
  STOCK_SPLIT: {
    term: 'Stock Split',
    simpleDefinition: 'A company divides each share into multiple smaller shares.',
    detailedDefinition: '10:1 split → ₹5,000 share becomes 10 × ₹500 shares. Total value unchanged. Makes stock more affordable for retail investors. Common for stocks with very high prices.',
    example: 'MRF at ₹1,40,000 per share — extremely expensive. A 100:1 split → ₹1,400/share. More accessible.',
    category: 'BASIC',
  },
  RIGHTS_ISSUE: {
    term: 'Rights Issue',
    simpleDefinition: 'A company offers new shares only to existing shareholders at a discount.',
    detailedDefinition: 'If you hold shares, you get the "right" to buy more at below-market price. You can accept (buy more), sell your rights to someone else, or let them expire. Rights issues dilute existing shareholders if not taken.',
    example: 'Company rights issue: 1 new share for every 5 held at ₹80 (market ₹120). Buy or sell rights worth ₹40 each.',
    category: 'BASIC',
  },
  PROMOTER_HOLDING: {
    term: 'Promoter Holding',
    simpleDefinition: 'What percentage of the company is owned by the founders/management.',
    detailedDefinition: 'Higher promoter holding = founders have skin in the game and are aligned with shareholders. Pledged promoter holding = promoters borrowed against shares = risky. Falling promoter holding = promoters selling = warning sign.',
    example: 'Reliance Industries promoter holding 50.3% — Mukesh Ambani owns half the company. Very high = confidence.',
    category: 'INDIA',
  },
  PLEDGE: {
    term: 'Promoter Pledge',
    simpleDefinition: 'When promoters use their own company shares as loan collateral.',
    detailedDefinition: 'Pledged shares = promoters borrowed money keeping shares as security. If company share price falls sharply, lenders can sell pledged shares → share price crashes further (vicious cycle). High pledge % = major risk.',
    example: 'Company with 40% promoter shares pledged. Stock falls 30% → lenders force-sell pledged shares → stock crashes another 40%. Avoid stocks with >20% pledge.',
    category: 'INDIA',
  },
  DELIVERY_VOLUME: {
    term: 'Delivery Volume',
    simpleDefinition: 'Trades where people actually keep the shares overnight vs just day-trading.',
    detailedDefinition: 'High delivery % (>60%) = long-term investors buying/selling = serious positions. Low delivery (< 30%) = mostly intraday traders, no conviction. A big price move on high delivery volume = institutional accumulation.',
    example: 'TATASTEEL: Volume 5M shares, Delivery 3.5M (70%) = strong buying with long-term intent.',
    category: 'INDIA',
  },
  DEMAT: {
    term: 'Demat Account',
    simpleDefinition: 'An electronic account that holds your shares digitally (like a bank account for stocks).',
    detailedDefinition: 'Before demat, shares were physical paper certificates. Now all shares are held digitally with CDSL or NSDL (India\'s depositories). You need demat account + trading account to buy/sell stocks.',
    example: 'Open demat with Zerodha, Groww, or Upstox. Your 100 TCS shares show up just like money in a bank account.',
    category: 'INDIA',
  },
  MARGIN: {
    term: 'Margin Trading',
    simpleDefinition: 'Using borrowed money from your broker to buy more shares than you can afford.',
    detailedDefinition: 'Broker lends you money to increase your buying power. Amplifies both gains AND losses. If shares fall, you face a margin call — must deposit more money or broker will sell your shares. Very risky for beginners.',
    example: 'You have ₹1 lakh. With 5× margin you can buy ₹5 lakh worth of shares. 20% fall = you lose entire ₹1 lakh + owe ₹0.',
    category: 'BASIC',
  },
  LEVERAGE: {
    term: 'Leverage',
    simpleDefinition: 'Using borrowed money or derivatives to control a large position with small capital.',
    detailedDefinition: '10× leverage means ₹1 lakh controls ₹10 lakh worth of stock. Small moves create large gains or losses. F&O (futures/options) provides natural leverage. Leverage is the fastest way to make and lose money.',
    example: 'Buy 1 Nifty futures lot (₹5L value) with ₹80,000 margin. 2% Nifty rise = ₹10,000 profit = 12.5% return. 2% fall = ₹10,000 loss.',
    category: 'BASIC',
  },
  SHORT_SELLING: {
    term: 'Short Selling',
    simpleDefinition: 'Selling shares you don\'t own, betting the price will fall so you can buy them back cheaper.',
    detailedDefinition: 'Borrow shares → sell at ₹500 → stock falls to ₹400 → buy at ₹400 → return shares → profit ₹100. Risk: unlimited loss if stock RISES instead. In India, allowed intraday only for most retail investors (through F&O for overnight).',
    example: 'Short sell 100 INFY at ₹1,500. INFY falls to ₹1,400. Buy back 100 shares = profit ₹10,000. If INFY rises to ₹1,600 → loss ₹10,000.',
    category: 'BASIC',
  },
  SIP: {
    term: 'SIP (Systematic Investment Plan)',
    simpleDefinition: 'Investing a fixed amount in mutual funds every month automatically.',
    detailedDefinition: 'Like an EMI but for investing. ₹5,000/month in a Nifty index fund over 20 years = massive wealth through compounding. Averages out market highs and lows (rupee cost averaging). Best strategy for beginners — set and forget.',
    example: '₹10,000/month SIP in Nifty 50 index fund for 15 years at 12% returns = ₹50 lakh corpus from ₹18 lakh invested.',
    category: 'INDIA',
  },
  MUTUAL_FUND: {
    term: 'Mutual Fund',
    simpleDefinition: 'A professionally managed pool of money invested across many stocks.',
    detailedDefinition: 'You buy units of a fund. Fund manager invests in 30-50+ stocks. Diversification reduces risk. Types: equity funds (stocks), debt funds (bonds), hybrid (both). SEBI-regulated. Good for beginners who don\'t want to pick individual stocks.',
    example: 'Nifty 50 Index Fund: invests in all 50 Nifty companies. 1% annual expense. 12-15% long-term returns historically.',
    category: 'INDIA',
  },
  ETF: {
    term: 'ETF (Exchange Traded Fund)',
    simpleDefinition: 'Like a mutual fund but traded on the stock exchange like a regular share.',
    detailedDefinition: 'Nifty BeES tracks Nifty 50 — buy/sell anytime during market hours at live prices. Lower expense ratio than mutual funds. No fund manager bias. Perfect for passive, low-cost investing.',
    example: 'Nifty 50 ETF (NIFTYBEES) trades at ₹216. Price moves exactly with Nifty. Expense ratio: 0.04%. Very cheap.',
    category: 'INDIA',
  },
  STT: {
    term: 'STT (Securities Transaction Tax)',
    simpleDefinition: 'A government tax charged every time you buy or sell shares.',
    detailedDefinition: 'For equity delivery: 0.1% on both buy and sell. For intraday: 0.025% on sell side only. For F&O: 0.0125% for futures, 0.0625% for options (on sell). Cannot be avoided — directly deducted by broker.',
    example: 'Buy ₹1,00,000 of HDFC Bank shares → pay ₹100 STT on buy + ₹100 STT on sell = ₹200 total tax.',
    category: 'INDIA',
  },
  LTCG: {
    term: 'LTCG (Long Term Capital Gains)',
    simpleDefinition: 'Tax on profit from selling stocks held for more than 1 year.',
    detailedDefinition: 'Profits above ₹1 lakh from equity (held >1 year) taxed at 10% (no indexation). Sell shares held 1+ year = LTCG tax. This is why "buy and hold" works — 10% tax is much lower than income tax on short-term gains.',
    example: 'Buy TCS at ₹3,000. Hold 14 months. Sell at ₹3,500. Profit ₹500/share × 100 shares = ₹50,000. Below ₹1L threshold = zero LTCG tax.',
    category: 'INDIA',
  },
  STCG: {
    term: 'STCG (Short Term Capital Gains)',
    simpleDefinition: 'Tax on profit from selling stocks held for less than 1 year.',
    detailedDefinition: 'Profits from selling equity within 12 months taxed at 15% flat (currently 20% after July 2024 budget). Always higher than LTCG. This encourages long-term holding over speculation.',
    example: 'Buy INFY at ₹1,400. Sell 8 months later at ₹1,700. Profit ₹300 × 200 shares = ₹60,000. STCG tax = ₹9,000 (15%).',
    category: 'INDIA',
  },
  F_AND_O: {
    term: 'F&O (Futures & Options)',
    simpleDefinition: 'Derivatives contracts to buy/sell stocks or indices at a future date — high risk, high reward.',
    detailedDefinition: 'Futures: obligation to buy/sell at price on expiry. Options: right (not obligation) to buy/sell. F&O requires SEBI F&O segment approval. Leverage is built-in. 95%+ F&O traders lose money — not for beginners.',
    example: 'Nifty Futures: Buy 1 lot (50 shares) at 19,500 with ₹80,000 margin. If Nifty rises to 19,700 = profit ₹10,000 (12.5% return in days).',
    category: 'INDIA',
  },
  LOT_SIZE: {
    term: 'Lot Size',
    simpleDefinition: 'The minimum number of shares in one F&O contract.',
    detailedDefinition: 'In F&O, you trade in lots, not individual shares. Nifty lot = 50 shares. Bank Nifty = 15 shares. You cannot trade less than 1 lot. This means F&O requires significant capital.',
    example: 'Nifty at 19,500. 1 lot = 50 shares. Contract value = 19,500 × 50 = ₹9,75,000. Margin needed = ~₹80,000-1,00,000.',
    category: 'INDIA',
  },
  OPEN_INTEREST: {
    term: 'Open Interest (OI)',
    simpleDefinition: 'The total number of active options/futures contracts that haven\'t been settled.',
    detailedDefinition: 'Rising OI + rising price = strong bullish trend (new money entering). Rising OI + falling price = strong bearish trend. Falling OI = traders closing positions. Max OI at a strike = strong support/resistance.',
    example: 'Nifty 19,500 CE has 50 lakh open interest — highest OI = strong resistance. Market unlikely to sustain above 19,500.',
    category: 'OPTIONS',
  },

  // ─── TECHNICAL ────────────────────────────────────────────────────────────

  RSI: {
    term: 'Relative Strength Index (RSI)',
    simpleDefinition: 'A number from 0-100 showing if a stock is overbought or oversold.',
    detailedDefinition: 'Above 70 = overbought (stock may fall soon). Below 30 = oversold (stock may rise). Between 40-60 = neutral, healthy trend. RSI divergence (price rising, RSI falling) is an early reversal warning.',
    example: 'INFY RSI at 75 — stock has risen a lot quickly. Watch for pullback. RSI below 30 = potential buying opportunity.',
    category: 'TECHNICAL',
  },
  MACD: {
    term: 'MACD (Moving Average Convergence Divergence)',
    simpleDefinition: 'Shows momentum — whether a stock is gaining or losing strength.',
    detailedDefinition: 'MACD line crosses above signal line = bullish momentum. Crosses below = bearish. Histogram bars show strength — green growing bars = accelerating bulls, red growing bars = accelerating bears.',
    example: 'TCS MACD crossed above signal line last week — momentum turning bullish. Next few days may see upward move.',
    category: 'TECHNICAL',
  },
  BOLLINGER_BANDS: {
    term: 'Bollinger Bands',
    simpleDefinition: 'Three lines showing a stock\'s normal price range.',
    detailedDefinition: 'Middle band = 20-day average. Upper/lower = standard deviation limits. Touch upper band = may be overbought. Touch lower band = oversold. Bands squeezing together = big move incoming (direction unknown).',
    example: 'Reliance touching upper Bollinger Band at ₹2,950 — caution, may face resistance here.',
    category: 'TECHNICAL',
  },
  SUPPORT: {
    term: 'Support Level',
    simpleDefinition: 'A price where a stock tends to stop falling and bounce back up.',
    detailedDefinition: 'Like a floor for the stock price. Buyers tend to step in at support levels. The more times a price has bounced from a level, the stronger the support. Breaking below support is bearish.',
    example: 'HDFC Bank has strong support at ₹1,600 — bounced 4 times from this level in 6 months.',
    category: 'TECHNICAL',
  },
  RESISTANCE: {
    term: 'Resistance Level',
    simpleDefinition: 'A price where a stock tends to stop rising and fall back.',
    detailedDefinition: 'Like a ceiling for the stock price. Sellers tend to appear at resistance levels. Breaking above resistance is very bullish — old resistance becomes new support after breakout.',
    example: 'Nifty 50 facing strong resistance at 20,000 — psychologically important level, sellers emerge here.',
    category: 'TECHNICAL',
  },
  SMA: {
    term: 'Simple Moving Average (SMA)',
    simpleDefinition: 'The average price of a stock over a set number of days.',
    detailedDefinition: 'SMA20 = average of last 20 days. SMA50 = last 50 days. SMA200 = last 200 days. Price above all three = strong uptrend. Crossing below SMA200 = serious bearish signal called "Death Cross".',
    example: 'If Nifty is above SMA20, SMA50 and SMA200 — market is in healthy uptrend. All three act as support levels.',
    category: 'TECHNICAL',
  },
  EMA: {
    term: 'Exponential Moving Average (EMA)',
    simpleDefinition: 'Like SMA but gives more importance to recent prices.',
    detailedDefinition: 'EMA reacts faster to recent price changes than SMA. EMA9 and EMA21 for short-term signals, EMA50 and EMA200 for trend direction. Golden Cross (50 EMA crossing above 200 EMA) = very bullish.',
    example: 'Stock crossing above EMA21 for first time in 3 weeks — short-term momentum shifting bullish.',
    category: 'TECHNICAL',
  },
  SUPERTREND: {
    term: 'Supertrend Indicator',
    simpleDefinition: 'A line that tells you if a stock is in an uptrend or downtrend.',
    detailedDefinition: 'Green line below price = uptrend, hold or buy. Red line above price = downtrend, avoid or sell. Very popular among Indian traders. Supertrend flipping from red to green = strong buy signal.',
    example: 'Supertrend flipped green on SBIN at ₹580 — stock went to ₹650 over next 3 weeks.',
    category: 'TECHNICAL',
  },
  VWAP: {
    term: 'VWAP (Volume Weighted Average Price)',
    simpleDefinition: 'The average price weighted by how much was traded at each price.',
    detailedDefinition: 'The "fair price" for the day based on volume. Institutions try to buy below VWAP and sell above. Price above VWAP = intraday bullish. Price below = bearish for the day. Resets every day.',
    example: 'RELIANCE VWAP at ₹2,845. Price at ₹2,860 (above VWAP) = intraday bulls in control.',
    category: 'TECHNICAL',
  },
  ATR: {
    term: 'Average True Range (ATR)',
    simpleDefinition: 'How much a stock typically moves in a day — its volatility measure.',
    detailedDefinition: 'High ATR = stock moves a lot daily (risky but more opportunity). Low ATR = stable, slow-moving. Use ATR to set stop losses: 1.5× ATR below entry is common. Stops too tight on high-ATR stocks get hit by normal noise.',
    example: 'TATASTEEL ATR = ₹35. A stop loss ₹10 below entry will get stopped out by normal fluctuation. Use ₹50 instead.',
    category: 'TECHNICAL',
  },
  FIBONACCI: {
    term: 'Fibonacci Retracement',
    simpleDefinition: 'Key price levels where stocks often pause or reverse, based on Fibonacci math.',
    detailedDefinition: 'Key levels: 23.6%, 38.2%, 50%, 61.8%, 78.6%. After a big up move, stocks often retrace to these levels before continuing. 61.8% is the "golden ratio" — strongest support.',
    example: 'Nifty rose from 18,000 to 20,000. 61.8% retracement = 18,764. Strong buyers expected here on pullback.',
    category: 'TECHNICAL',
  },
  CANDLESTICK: {
    term: 'Candlestick Chart',
    simpleDefinition: 'Each "candle" shows a stock\'s open, high, low, and close price for one period.',
    detailedDefinition: 'Green candle = price closed higher than opened (bullish). Red = closed lower (bearish). The "wick" shows highest and lowest point. Patterns from multiple candles can predict future moves.',
    example: 'A long green candle with small wicks = strong buying. Small candle with long wicks = indecision in market.',
    category: 'TECHNICAL',
  },
  GOLDEN_CROSS: {
    term: 'Golden Cross',
    simpleDefinition: 'When the 50-day average crosses above the 200-day average — very bullish.',
    detailedDefinition: 'One of the most watched signals by institutional investors. Suggests the short-term trend is now stronger than the long-term. Often followed by sustained upward movement. Opposite = Death Cross (bearish).',
    example: 'Nifty 50 Golden Cross in early 2023 — market went up 25% in the following 12 months.',
    category: 'TECHNICAL',
  },

  // ─── OPTIONS ──────────────────────────────────────────────────────────────

  CALL_OPTION: {
    term: 'Call Option (CE)',
    simpleDefinition: 'The right to buy a stock at a fixed price before a date.',
    detailedDefinition: 'Pay a premium to buy a Call. If the stock rises above your strike, you profit. Maximum loss = only the premium paid. Think of it as a "bet the stock will go up" with capped downside.',
    example: 'Buy RELIANCE 2900 CE at ₹95 premium. Reliance goes to ₹3,050: profit = (3050-2900-95)×250 = ₹13,750.',
    category: 'OPTIONS',
  },
  PUT_OPTION: {
    term: 'Put Option (PE)',
    simpleDefinition: 'The right to sell a stock at a fixed price before a date.',
    detailedDefinition: 'Pay a premium to buy a Put. If the stock falls below your strike, you profit. Used to protect existing holdings or profit from a falling stock. Maximum loss = premium paid only.',
    example: 'Buy NIFTY 19000 PE at ₹150. Nifty falls to 18,500: profit = (19000-18500-150)×50 = ₹17,500.',
    category: 'OPTIONS',
  },
  STRIKE_PRICE: {
    term: 'Strike Price',
    simpleDefinition: 'The fixed price at which you can buy (Call) or sell (Put) the stock.',
    detailedDefinition: 'The price agreed when buying an option. For Call, profit when market exceeds strike. For Put, profit when market falls below strike. ATM = At The Money (strike ≈ current price).',
    example: 'NIFTY at 19,450. Strike 19,500 CE = slightly OTM. Strike 19,000 CE = ITM. ITM options are safer but costlier.',
    category: 'OPTIONS',
  },
  PREMIUM: {
    term: 'Options Premium',
    simpleDefinition: 'The price you pay to buy an option contract.',
    detailedDefinition: 'Premium = Intrinsic Value + Time Value. Premium decays as expiry approaches (theta decay). Buy options when IV is low, sell when IV is high. Beginners should mostly buy options, not sell naked.',
    example: 'NIFTY 19500 CE premium = ₹85. For 1 lot (50 shares): total cost = ₹85 × 50 = ₹4,250. Maximum loss.',
    category: 'OPTIONS',
  },
  EXPIRY: {
    term: 'Expiry Date',
    simpleDefinition: 'The last date an options contract is valid.',
    detailedDefinition: 'NSE options expire every Thursday (weekly) and last Thursday of month (monthly). As expiry approaches, time value decays faster. Avoid buying options <7 days to expiry — time decay is brutal.',
    example: 'Weekly expiry every Thursday. On expiry day, options worth only intrinsic value. Time value = zero.',
    category: 'OPTIONS',
  },
  IV: {
    term: 'Implied Volatility (IV)',
    simpleDefinition: 'How much the market expects the stock to move — affects option prices.',
    detailedDefinition: 'High IV = options are expensive (big move expected). Low IV = cheap options. Strategy: BUY when IV is low, SELL when IV is high. India VIX is the IV of Nifty options.',
    example: 'Before election results, Nifty IV jumped to 35% — options very expensive. After results, IV crashed to 12%.',
    category: 'OPTIONS',
  },
  DELTA: {
    term: 'Delta',
    simpleDefinition: 'How much an option price changes for every ₹1 move in the stock.',
    detailedDefinition: 'Delta 0.5 = option gains ₹0.50 for every ₹1 the stock rises. ATM options ≈ 0.5. Deep ITM ≈ 0.9. OTM ≈ 0.2. Buy ATM options (delta 0.4-0.6) for best balance of cost and sensitivity.',
    example: 'You own HDFC 1700 CE with delta 0.45. HDFC rises ₹20 → option gains ₹20 × 0.45 = ₹9.',
    category: 'OPTIONS',
  },
  THETA: {
    term: 'Theta (Time Decay)',
    simpleDefinition: 'How much value an option loses each day just due to time passing.',
    detailedDefinition: 'Options lose value every day even if stock doesn\'t move. Theta accelerates in the last 7 days before expiry. Option BUYERS lose theta. Option SELLERS collect theta. This is why selling options can be profitable.',
    example: 'You buy NIFTY CE for ₹100 premium. Theta = ₹3/day. In 10 days without stock moving = option worth ₹70.',
    category: 'OPTIONS',
  },
  PCR: {
    term: 'Put-Call Ratio (PCR)',
    simpleDefinition: 'Compares how many puts vs calls are being traded — shows market sentiment.',
    detailedDefinition: 'PCR > 1 = more puts being bought = bearish sentiment (but extreme PCR can signal bottom). PCR < 0.7 = more calls = bullish but risk of overconfidence. PCR 0.8-1.0 = neutral.',
    example: 'PCR of 1.5 on Nifty = excessive fear. Historically, Nifty bounced strongly when PCR exceeded 1.5.',
    category: 'OPTIONS',
  },
  MAX_PAIN: {
    term: 'Max Pain',
    simpleDefinition: 'The price where options sellers make maximum profit on expiry day.',
    detailedDefinition: 'Theory: on expiry, index/stock gravitates toward the price where most options expire worthless — causing max loss for options buyers and max gain for sellers. Not always accurate but widely watched.',
    example: 'Nifty max pain at 19,500 with Nifty at 19,700. Watch if Nifty drifts down toward 19,500 near Thursday expiry.',
    category: 'OPTIONS',
  },
  IRON_CONDOR: {
    term: 'Iron Condor',
    simpleDefinition: 'An options strategy that profits when a stock stays within a price range.',
    detailedDefinition: 'Sell call at higher strike + buy call further up + sell put at lower strike + buy put further down. Collect net premium. Profit if price stays between the two sold strikes at expiry.',
    example: 'Nifty Iron Condor: Sell 19200 PE + Buy 19000 PE + Sell 19600 CE + Buy 19800 CE. Collect ₹150. Profit if Nifty stays 19,050-19,750 on expiry.',
    category: 'OPTIONS',
  },
  BULL_CALL_SPREAD: {
    term: 'Bull Call Spread',
    simpleDefinition: 'Buy a lower strike Call, sell a higher one — cheaper way to bet on upside.',
    detailedDefinition: 'Reduces cost by giving up some profit potential. Max profit = difference between strikes minus premium paid. Max loss = premium paid. Good for beginners — defined risk, defined reward.',
    example: 'Buy RELIANCE 2900 CE at ₹95, Sell 3000 CE at ₹45. Net cost ₹50. Max profit ₹50/share (₹12,500 per lot).',
    category: 'OPTIONS',
  },

  // ─── MACRO ────────────────────────────────────────────────────────────────

  GDP: {
    term: 'GDP (Gross Domestic Product)',
    simpleDefinition: 'The total value of everything produced in a country in one year.',
    detailedDefinition: 'Higher GDP growth = economy expanding = good for stocks. India GDP growing at 7%+ is one of fastest globally. Stock markets generally rise when GDP grows and fall in recession (negative GDP growth).',
    example: 'India GDP growth 7.6% in 2023-24 — economy growing faster than most countries. Very positive for Nifty.',
    category: 'MACRO',
  },
  INFLATION: {
    term: 'Inflation (CPI)',
    simpleDefinition: 'How fast prices are rising, measured as Consumer Price Index.',
    detailedDefinition: 'India targets CPI at 4% (±2%). Above 6% = RBI may hike rates = bad for markets. Below 2% = RBI may cut rates = good for markets. High inflation hurts company margins and consumer spending.',
    example: 'CPI at 4.8% — within RBI comfort zone. No rate hike expected. Positive for rate-sensitive sectors like banking.',
    category: 'MACRO',
  },
  INDIA_VIX: {
    term: 'India VIX',
    simpleDefinition: 'India\'s fear index — measures expected volatility of Nifty options.',
    detailedDefinition: 'Below 15 = calm market, options cheap. 15-20 = moderate uncertainty. Above 20 = fearful market, options expensive. Very high VIX (>25) often marks market bottoms historically.',
    example: 'India VIX spiked to 30 during COVID crash in March 2020. Within 6 months, Nifty doubled as VIX fell to 15.',
    category: 'INDIA',
  },
  RBI_REPO: {
    term: 'RBI Repo Rate',
    simpleDefinition: 'The interest rate at which RBI lends money to banks.',
    detailedDefinition: 'When RBI increases repo rate: loans become expensive, spending slows, inflation cools — but markets may fall short-term. When RBI cuts rate: loans become cheap, economy grows, markets typically rise.',
    example: 'RBI cut repo rate from 6.5% to 6.25% → bank loan rates fall → consumers spend more → economy grows → Nifty rises.',
    category: 'INDIA',
  },

  // ─── INDIA ────────────────────────────────────────────────────────────────

  CIRCUIT_BREAKER: {
    term: 'Circuit Breaker',
    simpleDefinition: 'An automatic pause in trading when a stock moves too fast.',
    detailedDefinition: 'NSE/BSE halt trading if a stock rises or falls beyond 5%, 10%, or 20% in a day. Prevents panic selling. Upper circuit = stock cannot go higher. Lower circuit = cannot go lower that session.',
    example: 'Small-cap stock hits upper circuit at +20% — you cannot buy more that day. Strong demand signal.',
    category: 'INDIA',
  },
  FII: {
    term: 'Foreign Institutional Investors (FII)',
    simpleDefinition: 'Large foreign funds (like US mutual funds) buying/selling Indian stocks.',
    detailedDefinition: 'When FIIs buy heavily, it pushes Nifty up. When they sell (FII outflow), Nifty usually falls. They move billions of rupees — their decisions significantly impact Indian markets.',
    example: 'FII bought ₹5,000 crore in October — Nifty rose 3% that month.',
    category: 'INDIA',
  },
  DII: {
    term: 'Domestic Institutional Investors (DII)',
    simpleDefinition: 'Indian mutual funds and insurance companies buying stocks.',
    detailedDefinition: 'DIIs often buy when FIIs sell, providing market stability. SBI Mutual Fund, LIC, HDFC MF are major DIIs. Strong DII buying = long-term confidence in Indian markets.',
    example: 'LIC invested ₹3,000 crore when market fell 10% — DIIs absorbed FII selling pressure, preventing bigger crash.',
    category: 'INDIA',
  },
  SEBI: {
    term: 'SEBI',
    simpleDefinition: 'Securities and Exchange Board of India — the stock market regulator.',
    detailedDefinition: 'SEBI makes rules for stock markets, protects investors, and regulates brokers, mutual funds, and companies. Like RBI is to banking, SEBI is to stock markets. Always verify your broker is SEBI-registered.',
    example: 'SEBI introduced T+1 settlement — you get money 1 day after selling shares instead of 2 days.',
    category: 'INDIA',
  },

  // ─── CRYPTO ───────────────────────────────────────────────────────────────

  DOMINANCE: {
    term: 'Bitcoin Dominance',
    simpleDefinition: 'What percentage of all crypto market value is Bitcoin.',
    detailedDefinition: 'High dominance (>60%) = investors prefer Bitcoin safety. Low dominance = altcoin season — smaller coins outperforming Bitcoin. Falling dominance often means good time for ETH, SOL, etc.',
    example: 'BTC dominance dropped from 55% to 45% in Jan 2024 — altcoins like SOL and AVAX surged 3-4× in same period.',
    category: 'CRYPTO',
  },

  // ─── WEATHER ──────────────────────────────────────────────────────────────

  UV_INDEX: {
    term: 'UV Index',
    simpleDefinition: 'How strong the sun\'s ultraviolet radiation is.',
    detailedDefinition: '0-2: Low (safe). 3-5: Moderate (wear sunscreen). 6-7: High (protection essential). 8-10: Very High. 11+: Extreme. In India, UV often reaches 8-10 during summer months.',
    example: 'Mumbai UV Index 9 at noon in May — wear SPF 50+ sunscreen and avoid direct sun 11am-3pm.',
    category: 'BASIC',
  },
  HUMIDITY: {
    term: 'Humidity',
    simpleDefinition: 'How much moisture is in the air — affects how hot it actually feels.',
    detailedDefinition: '100% humidity = air fully saturated with water. High humidity makes it feel hotter (body can\'t cool by sweating). Mumbai at 85% humidity + 32°C feels like 40°C. Low humidity makes cold feel colder.',
    example: 'Delhi 40°C at 20% humidity (dry heat) feels more bearable than Mumbai 32°C at 90% humidity.',
    category: 'BASIC',
  },
  FEELS_LIKE: {
    term: 'Feels Like Temperature',
    simpleDefinition: 'The temperature your body actually experiences, accounting for wind and humidity.',
    detailedDefinition: 'Also called "apparent temperature". High humidity makes it feel hotter. Strong wind makes cold feel colder (wind chill). This is the number that matters for what to wear.',
    example: 'Delhi is 38°C but Feels Like 42°C due to high humidity. Choose clothes based on feels like, not actual temp.',
    category: 'BASIC',
  },
}
