export type ThemeName = 'dark' | 'dark-contrast' | 'light' | 'system';

export interface Theme {
  name: ThemeName;
  label: string;
  description: string;
  icon: string;
  previewColors: string[];
  vars: Record<string, string>;
}

export const THEMES: Record<Exclude<ThemeName, 'system'>, Theme> = {
  'dark': {
    name: 'dark',
    label: 'Dark',
    description: 'Bloomberg terminal style',
    icon: '🌙',
    previewColors: ['#000000', '#050a05', '#ff6d00'],
    vars: {
      '--bg-terminal':    '#000000',
      '--bg-panel':       '#050a05',
      '--bg-header':      '#0a140a',
      '--bg-hover':       '#0f1f0f',
      '--bg-row-hover':   '#0f1f0f',
      '--bg-input':       '#0a140a',
      '--bg-card':        '#050a05',
      '--bg-tooltip':     '#0a140a',
      '--bg-overlay':     'rgba(0,0,0,0.88)',
      '--bg-badge-buy':   '#003300',
      '--bg-badge-sell':  '#330000',
      '--bg-badge-hold':  '#332200',
      '--text-primary':   '#c8e6c9',
      '--text-secondary': '#88aa88',
      '--text-muted':     '#607d8b',
      '--text-accent':    '#ff6d00',
      '--text-gold':      '#f59e0b',
      '--text-positive':  '#00e676',
      '--text-negative':  '#ff1744',
      '--text-neutral':   '#88aa88',
      '--text-warning':   '#ff9800',
      '--text-info':      '#40c4ff',
      '--text-buy':       '#00e676',
      '--text-sell':      '#ff1744',
      '--text-hold':      '#ff9800',
      '--border-dim':     '#1b2e1b',
      '--border-color':   '#1b2e1b',
      '--border-medium':  '#2e5a2e',
      '--border-bright':  '#2e5a2e',
      '--border-terminal':'#1b2e1b',
      '--border-accent':  '#ff6d00',
      '--border-panel':   '#1b2e1b',
      '--scrollbar-track':'#0a140a',
      '--scrollbar-thumb':'#1b2e1b',
      '--scrollbar-hover':'#2e5a2e',
      '--tooltip-bg':     '#0a140a',
      '--tooltip-border': '#ff6d00',
      '--badge-buy-bg':   '#003300',
      '--badge-buy-text': '#00e676',
      '--badge-sell-bg':  '#330000',
      '--badge-sell-text':'#ff1744',
      '--chart-bg':       '#050a05',
      '--chart-grid':     '#1b2e1b',
      '--chart-text':     '#607d8b',
      '--chart-up':       '#00e676',
      '--chart-down':     '#ff1744',
      '--overlay-bg':     'rgba(0,0,0,0.88)',
      '--glow-accent':    'rgba(255,109,0,0.12)',
      '--glow-cyan':      'rgba(255,109,0,0.12)',
      '--glow-green':     'rgba(0,230,118,0.12)',
      '--glow-red':       'rgba(255,23,68,0.12)',
      '--glow-gold':      'rgba(245,158,11,0.12)',
    },
  },
  'dark-contrast': {
    name: 'dark-contrast',
    label: 'Dark High Contrast',
    description: 'Maximum contrast for accessibility',
    icon: '⬛',
    previewColors: ['#000000', '#ffffff', '#ff8c00'],
    vars: {
      '--bg-terminal':    '#000000',
      '--bg-panel':       '#0a0a0a',
      '--bg-header':      '#000000',
      '--bg-hover':       '#1a1a1a',
      '--bg-row-hover':   '#1a1a1a',
      '--bg-input':       '#111111',
      '--bg-card':        '#0a0a0a',
      '--bg-tooltip':     '#000000',
      '--bg-overlay':     'rgba(0,0,0,0.95)',
      '--bg-badge-buy':   '#003d00',
      '--bg-badge-sell':  '#3d0000',
      '--bg-badge-hold':  '#3d2200',
      '--text-primary':   '#ffffff',
      '--text-secondary': '#dddddd',
      '--text-muted':     '#aaaaaa',
      '--text-accent':    '#ff8c00',
      '--text-gold':      '#ffaa00',
      '--text-positive':  '#00ff41',
      '--text-negative':  '#ff3333',
      '--text-neutral':   '#cccccc',
      '--text-warning':   '#ffaa00',
      '--text-info':      '#00ccff',
      '--text-buy':       '#00ff41',
      '--text-sell':      '#ff3333',
      '--text-hold':      '#ffaa00',
      '--border-dim':     '#555555',
      '--border-color':   '#555555',
      '--border-medium':  '#888888',
      '--border-bright':  '#888888',
      '--border-terminal':'#444444',
      '--border-accent':  '#ff8c00',
      '--border-panel':   '#444444',
      '--scrollbar-track':'#111111',
      '--scrollbar-thumb':'#444444',
      '--scrollbar-hover':'#666666',
      '--tooltip-bg':     '#000000',
      '--tooltip-border': '#ff8c00',
      '--badge-buy-bg':   '#004400',
      '--badge-buy-text': '#00ff41',
      '--badge-sell-bg':  '#440000',
      '--badge-sell-text':'#ff3333',
      '--chart-bg':       '#000000',
      '--chart-grid':     '#333333',
      '--chart-text':     '#aaaaaa',
      '--chart-up':       '#00ff41',
      '--chart-down':     '#ff3333',
      '--overlay-bg':     'rgba(0,0,0,0.95)',
      '--glow-accent':    'rgba(255,140,0,0.2)',
      '--glow-cyan':      'rgba(0,204,255,0.2)',
      '--glow-green':     'rgba(0,255,65,0.2)',
      '--glow-red':       'rgba(255,51,51,0.2)',
      '--glow-gold':      'rgba(255,170,0,0.2)',
    },
  },
  'light': {
    name: 'light',
    label: 'Light',
    description: 'Clean light theme for daytime',
    icon: '☀️',
    previewColors: ['#f0f4f0', '#ffffff', '#cc4400'],
    vars: {
      '--bg-terminal':    '#f0f4f0',
      '--bg-panel':       '#ffffff',
      '--bg-header':      '#e8ede8',
      '--bg-hover':       '#f5f8f5',
      '--bg-row-hover':   '#f5f8f5',
      '--bg-input':       '#ffffff',
      '--bg-card':        '#ffffff',
      '--bg-tooltip':     '#fffef5',
      '--bg-overlay':     'rgba(230,240,230,0.92)',
      '--bg-badge-buy':   '#e6f4e6',
      '--bg-badge-sell':  '#fce8e8',
      '--bg-badge-hold':  '#fff3e0',
      '--text-primary':   '#111111',
      '--text-secondary': '#444444',
      '--text-muted':     '#777777',
      '--text-accent':    '#cc4400',
      '--text-gold':      '#886600',
      '--text-positive':  '#006600',
      '--text-negative':  '#cc0000',
      '--text-neutral':   '#555555',
      '--text-warning':   '#aa5500',
      '--text-info':      '#0044aa',
      '--text-buy':       '#006600',
      '--text-sell':      '#cc0000',
      '--text-hold':      '#aa5500',
      '--border-dim':     '#d0d8d0',
      '--border-color':   '#d0d8d0',
      '--border-medium':  '#aabbaa',
      '--border-bright':  '#aabbaa',
      '--border-terminal':'#dddddd',
      '--border-accent':  '#cc4400',
      '--border-panel':   '#dddddd',
      '--scrollbar-track':'#eeeeee',
      '--scrollbar-thumb':'#cccccc',
      '--scrollbar-hover':'#aaaaaa',
      '--tooltip-bg':     '#fffef0',
      '--tooltip-border': '#cc4400',
      '--badge-buy-bg':   '#e8f5e8',
      '--badge-buy-text': '#006600',
      '--badge-sell-bg':  '#fce8e8',
      '--badge-sell-text':'#cc0000',
      '--chart-bg':       '#ffffff',
      '--chart-grid':     '#eeeeee',
      '--chart-text':     '#666666',
      '--chart-up':       '#006600',
      '--chart-down':     '#cc0000',
      '--overlay-bg':     'rgba(230,240,230,0.92)',
      '--glow-accent':    'rgba(204,68,0,0.08)',
      '--glow-cyan':      'rgba(0,68,170,0.08)',
      '--glow-green':     'rgba(0,102,0,0.08)',
      '--glow-red':       'rgba(204,0,0,0.08)',
      '--glow-gold':      'rgba(136,102,0,0.08)',
    },
  },
};

export function getSystemThemeVars(): Record<string, string> {
  if (typeof window === 'undefined') return THEMES.dark.vars;
  return window.matchMedia('(prefers-color-scheme: dark)').matches
    ? THEMES.dark.vars
    : THEMES.light.vars;
}

export function getThemeVars(theme: ThemeName): Record<string, string> {
  if (theme === 'system') return getSystemThemeVars();
  return THEMES[theme]?.vars ?? THEMES.dark.vars;
}
